# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProcessingEngine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvhrEndPoint',
            fields=[
                ('endpoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ProcessingEngine.EndPoint')),
            ],
            options={
                'verbose_name': 'EVHR End Point',
                'verbose_name_plural': 'EVHR End Points',
            },
            bases=('ProcessingEngine.endpoint',),
        ),
        migrations.CreateModel(
            name='EvhrProtocol',
            fields=[
                ('protocol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ProcessingEngine.Protocol')),
            ],
            options={
                'verbose_name': 'EVHR Protocol',
                'verbose_name_plural': 'EVHR Protocols',
            },
            bases=('ProcessingEngine.protocol',),
        ),
    ]
