# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 18:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.FileField(help_text="The file path for this constituent's disk file.", upload_to=b'')),
                ('started', models.BooleanField(default=False)),
                ('url', models.URLField(help_text="The URL of this constituent's file", validators=[django.core.validators.URLValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='ConstituentProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(null=True)),
                ('constituent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ProcessingEngine.Constituent')),
            ],
            options={
                'verbose_name': 'Constituent Process',
                'verbose_name_plural': 'Constituent Processes',
            },
        ),
        migrations.CreateModel(
            name='EndPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the end point', max_length=80, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(80)])),
                ('serviceId', models.CharField(blank=True, help_text='Indicates a named subset of the data provided by this end point', max_length=80, null=True, validators=[django.core.validators.MaxLengthValidator(80)])),
                ('url', models.URLField(help_text='The base URL of this end point', validators=[django.core.validators.URLValidator()])),
                ('version', models.CharField(blank=True, default='1.0.0', help_text="The version of the end point's API to use", max_length=10, null=True, validators=[django.core.validators.MaxLengthValidator(10)])),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'End Point',
                'verbose_name_plural': 'End Points',
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=80)),
                ('className', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('started', models.BooleanField(default=False)),
                ('aggregationComplete', models.BooleanField(default=False)),
                ('destination', models.FileField(help_text="The file path for this request's disk files.", upload_to=b'')),
                ('startDate', models.DateField(blank=True, help_text='Earliest date to retrieve', null=True)),
                ('endDate', models.DateField(blank=True, help_text='Latest date to retrieve', null=True)),
                ('endPoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProcessingEngine.EndPoint')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RequestProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ProcessingEngine.Request')),
            ],
            options={
                'verbose_name': 'Request Process',
                'verbose_name_plural': 'Request Processes',
            },
        ),
        migrations.AddField(
            model_name='endpoint',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProcessingEngine.Protocol'),
        ),
        migrations.AddField(
            model_name='constituentprocess',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProcessingEngine.RequestProcess'),
        ),
        migrations.AddField(
            model_name='constituent',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProcessingEngine.Request'),
        ),
        migrations.AlterUniqueTogether(
            name='endpoint',
            unique_together=set([('name', 'url')]),
        ),
    ]
