# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ProcessingEngine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
