# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDaemonProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Job Daemon Process',
                'verbose_name_plural': 'Job Daemon Processes',
            },
        ),
    ]
