# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 18:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProcessingEngine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoEndPoint',
            fields=[
                ('endpoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ProcessingEngine.EndPoint')),
            ],
            options={
                'verbose_name': 'Geo End Point',
                'verbose_name_plural': 'Geo End Points',
            },
            bases=('ProcessingEngine.endpoint',),
        ),
        migrations.CreateModel(
            name='GeoProtocol',
            fields=[
                ('protocol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ProcessingEngine.Protocol')),
            ],
            options={
                'verbose_name': 'Geo Protocol',
                'verbose_name_plural': 'Geo Protocols',
            },
            bases=('ProcessingEngine.protocol',),
        ),
        migrations.CreateModel(
            name='GeoRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ProcessingEngine.Request')),
                ('ulx', models.DecimalField(decimal_places=8, help_text='Upper-left X ordinate for the request', max_digits=20, validators=[django.core.validators.DecimalValidator(12, 8)])),
                ('uly', models.DecimalField(decimal_places=8, help_text='Upper-left Y ordinate for the request', max_digits=20, validators=[django.core.validators.DecimalValidator(12, 8)])),
                ('lrx', models.DecimalField(decimal_places=8, help_text='Lower-right X ordinate for the request', max_digits=20, validators=[django.core.validators.DecimalValidator(12, 8)])),
                ('lry', models.DecimalField(decimal_places=8, help_text='Lower-right Y ordinate for the request', max_digits=20, validators=[django.core.validators.DecimalValidator(12, 8)])),
                ('srs', models.CharField(help_text='The OGC well-known text definition of the spatial reference system describing ulx, uly, lrx and lry.', max_length=80)),
                ('outSRS', models.CharField(blank=True, help_text='The OGC well-known text definition of the spatial reference system describing the output products.', max_length=80, null=True)),
            ],
            options={
                'verbose_name': 'Geo Request',
                'verbose_name_plural': 'Geo Requests',
            },
            bases=('ProcessingEngine.request',),
        ),
        migrations.CreateModel(
            name='LandsatMetadata',
            fields=[
                ('acquisitionDate', models.DateField()),
                ('sceneID', models.CharField(max_length=21)),
                ('productID', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('path', models.IntegerField()),
                ('row', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Landsat Metadata',
                'verbose_name_plural': 'Landsat Metadata',
            },
        ),
    ]
