# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoProcessingEngine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='georequest',
            name='outSRS',
            field=models.CharField(blank=True, help_text='The OGC well-known text definition of the spatial reference system describing the output products.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='georequest',
            name='srs',
            field=models.CharField(help_text='The OGC well-known text definition of the spatial reference system describing ulx, uly, lrx and lry.', max_length=1000),
        ),
    ]
